# Generated by Django 5.1.3 on 2024-12-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('spot_name', models.CharField(max_length=50)),
                ('course_seq', models.IntegerField()),
                ('time_move', models.IntegerField()),
                ('div_inout', models.CharField(max_length=5)),
                ('tema_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.course')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.region')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measure', models.IntegerField()),
                ('avg_humidity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('avg_windspeed', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('min_temperature', models.DecimalField(decimal_places=1, max_digits=5)),
                ('precipitation', models.DecimalField(decimal_places=1, max_digits=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.region')),
            ],
            options={
                'unique_together': {('region', 'date_measure')},
            },
        ),
    ]
